export { default as API } from './api';
// export { default as CityService } from './cities';
export { default as ContentService } from './content';
export { default as Device } from './device';
export { default as ErrorService } from './error';
export { default as FileCache } from './fileCache';
export { default as LanguageService } from './language';
export { default as Navigator } from './navigator';
export { default as PermissionsService } from './permissions';
export { default as RoleService } from './roles';
export { default as Toastify } from './toastify';
export { default as TokenService } from './token';
export { default as Yup } from './yup';
